version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slimphp_app5
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "8085:8080"
    depends_on:
      - db
    networks:
      - slimnetwork
    command: php -S 0.0.0.0:8080 -t public

  db:
    image: postgres:15
    container_name: slimphp_db5
    restart: always
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - slimnetwork
volumes:
  pgdata:
networks:
  slimnetwork:
    driver: bridge

